# Generated by Django 5.0.1 on 2026-01-21 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkfit', '0003_fitnessvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0.0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('calories', models.PositiveIntegerField(default=0, help_text='Estimated kcal')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Optional session identifier', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitness_records', to='walkfit.register')),
            ],
            options={
                'verbose_name': 'Fitness Record',
                'verbose_name_plural': 'Fitness Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
