# Generated by Django 5.2.10 on 2026-01-23 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkfit', '0004_fitnessrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fitnessrecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walkfit.register'),
        ),
    ]
