# Generated by Django 5.2.10 on 2026-01-23 08:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkfit', '0005_alter_fitnessrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_water', models.BooleanField(default=True)),
                ('remind_exercise', models.BooleanField(default=True)),
                ('remind_diet', models.BooleanField(default=True)),
                ('remind_time', models.TimeField(default=datetime.time(9, 0))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walkfit.register')),
            ],
        ),
    ]
