# Generated by Django 5.2.10 on 2026-01-23 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkfit', '0006_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
